#!/usr/bin/env bash
set -e

SOURCE=${BASH_SOURCE[0]}
while [ -L "$SOURCE" ]; do
    DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
    SOURCE=$(readlink "$SOURCE")
    [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE
done
DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )

cd ${DIR}

if [ "$1" == "git" ]; then

    exec git ${@:2}

elif [ "$1" == "out" ]; then

    TIME="OUT $(date --rfc-3339=seconds)"

    echo "${TIME}" >> current.txt

    git reset > /dev/null
    git add current.txt
    git commit -m "${TIME}"

elif [ "$1" == "in" ]; then

    TIME="IN $(date --rfc-3339=seconds)"
    
    echo "${TIME}" >> current.txt

    git reset > /dev/null
    git add current.txt
    git commit -m "${TIME}"

elif [ "$1" == "rotate" ]; then

    TODAY_TXT=$(date --rfc-3339=date).txt
    cat current.txt >> ${TODAY_TXT}
    : > current.txt

    git reset > /dev/null
    git add current.txt
    git add ${TODAY_TXT}
    git commit -m "ROTATE"

elif [ -z "$1" ]; then

    exec more current.txt

else

    echo "Unknown argument: $1"
    exit 1

fi
